### ISSUE TITLE
Nil not redefinable

### ISSUE THREAD

**Issue by tromp** [chatziko/lci#13] opened 2023-08-07 17:06 UTC
I chose a different representation of Nil in .lcirc, and redefined IsNil accordingly, but found that the runtime no longer recognizes it. This would work if the runtime also used the IsNil check to test for Nil...

**Comment by chatziko** [comment] 2024-12-12 10:49
This is weird, maybe there is a hard-coded check somewhere. Can you send your representation so that I can reproduce the issue?

**Comment by tromp** [comment] 2024-12-12 11:20
Sorry; I don't remember what I meant by "the runtime no longer recognizes it".
But I'm pretty sure that the new definitions I tried were

Nil = False;
IsNil = \p.p (\x.\y.\t. False) True;

Does the runtime even depend on the contents of ./lcirc ?

**Comment by chatziko** [comment] 2024-12-14 14:36
Now I understand the issue, the runtime does **not** depend on the definitions in .lcirc, and it works fine after redefining `Nil`. However the pretty-print (displaying `[1,2]` instead of the encoding of the list) does depend on the encoding, because it has to decide for every arbitrary term whether it is a list or not. It cannot use `IsNil` because it doesn't even know that the term is a list.

I tried queens.lci with your definitions, it works fine, it just doesn't pretty-print the result.

So I'm closing this cause the core functionality is ok, and the pretty-print is not easy to be made generic, especially given that your `Nil` coinsides with `0` and we wouldn't want every zero to be shown as `[]`.

**Closed as completed by chatziko** 2024-12-14 14:36 UTC
